config/routes.rb
Wasteblue::Application.routes.draw do

  resources :categories

  match "/done" => "purchasing_ads#done"
  match "/atualizar_endereco" => "purchasing_ads#atualizar_endereco"

  get "users/show"

  get "users/index"

  get "legal_entities/show"

  get "legal_entities/index"

  get "faq/view"

  get "policy/view"

  get "terms/view"

  get "press/view"

  get "partners/view"

  get "about/view"

  get "awasteblue/view"

  get "login" => "awasteblue#login"

  get "cadastrar" => "awasteblue#cadastrar"

  get "ads/all"

  get "advertise/index"

  get "howto/index"

  get "blog/index"

  get "contato/index"
  get "construction/index"
  
  devise_for :legal_entities
  devise_for :users

  devise_scope :legal_entity do
    get 'pessoa_juridica/sign_in', :to => 'devise/sessions#new', :as => :new_legal_entity_session
    get 'pessoa_juridica/sign_up', :to => 'devise/registrations#new', :as => :new_legal_entity_registration
    get 'pessoa_juridica/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_legal_entity_session
  end

  devise_scope :user do
    get 'pessoa_fisica/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'pessoa_fisica/sign_up', :to => 'devise/registrations#new', :as => :new_user_registration
    get 'pessoa_fisica/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match 'pessoa_juridica/conta/:id' => 'legal_entities#show'
  match 'pessoa_fisica/conta/:id' => 'users#show'

  match 'pessoa_juridica/conta/:id/editar' => 'legal_entities#edit'
  match 'pessoa_fisica/conta/:id/editar' => 'users#edit'

  match 'pessoa_juridica/conta/:id/criar_anuncio/venda' => 'sales_ads#new'
  match 'pessoa_fisica/conta/:id/criar_anuncio/venda' => 'sales_ads#new'

  match 'pessoa_juridica/conta/:id/criar_anuncio/compra' => 'purchasing_ads#new'
  match 'pessoa_fisica/conta/:id/criar_anuncio/compra' => 'purchasing_ads#new'

  resources :legal_entities
  resources :posts
  resources :users
  resources :sales_ads
  resources :purchasing_ads

 
  root :to => 'pages#index'

end

app/models/sales_ad.rb
class SalesAd < ActiveRecord::Base
  has_steps :steps => %w{ waste_description title_details price_quantity_frequency sample_transport_address }

  attr_accessible :category_id, :title, :user_type, :waste_origin, :details, :quantity,:unit,:unit_price,:total_price,:show_price,:frequency_removal_waste,:contract_time,:today_waste,:transportation_sample,:waste_address,:postal_code,:address_complete,:district,:state,:city,:current_step,:waste_name


  def validate_waste_description
    self.validates_presence_of :category_id
    self.validates_presence_of :waste_name
  end

  def validate_title_details
    self.validates_presence_of :title
    self.validates_presence_of :waste_origin
    self.validates_presence_of :details
  end

  def validate_price_quantity_frequency
    self.validates_presence_of :quantity
    self.validates_presence_of :unit
    self.validates_presence_of :unit_price
    self.validates_presence_of :total_price
    self.validates_presence_of :show_price
    self.validates_inclusion_of :show_price, :in => [true, false]
    self.validates_presence_of :frequency_removal_waste
    self.validates_presence_of :contract_time
  end

  def validate_sample_transport_address
    self.validates_presence_of :today_waste
    self.validates_presence_of :transportation_sample
    self.validates_presence_of :waste_address
    self.validates_presence_of :postal_code
    self.validates_presence_of :address_complete
    self.validates_presence_of :district
    self.validates_presence_of :state
    self.validates_presence_of :city
  end
end

app/controllers/sales_ads_controller.rb
class SalesAdsController < ApplicationController
  has_steps
  # GET /sales_ads
  # GET /sales_ads.json
  def index
    @sales_ads = SalesAd.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sales_ads }
    end
  end

  # GET /sales_ads/1
  # GET /sales_ads/1.json
  def show
    @sales_ad = SalesAd.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sales_ad }
    end
  end

  # GET /sales_ads/new
  # GET /sales_ads/new.json
  def new
    @sales_ad = SalesAd.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sales_ad }
    end
  end

  # GET /sales_ads/1/edit
  def edit
    @sales_ad = SalesAd.find(params[:id])
  end

  # POST /sales_ads
  # POST /sales_ads.json
  #def create
  #  @sales_ad = SalesAd.new(params[:sales_ad])

  #  respond_to do |format|
  #    if @sales_ad.save
  #      format.html { redirect_to @sales_ad, notice: 'Sales ad was successfully created.' }
  #      format.json { render json: @sales_ad, status: :created, location: @sales_ad }
  #    else
  #      format.html { render action: "new" }
  #      format.json { render json: @sales_ad.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # PUT /sales_ads/1
  # PUT /sales_ads/1.json
  #def update
  #  @sales_ad = SalesAd.find(params[:id])
  #  
  #  respond_to do |format|
  #    if @sales_ad.update_attributes(params[:sales_ad])
  #      format.html { redirect_to @sales_ad, notice: 'Sales ad was successfully updated.' }
  #      format.json { head :no_content }
  #    else
  #      format.html { render action: "edit" }
  #      format.json { render json: @sales_ad.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /sales_ads/1
  # DELETE /sales_ads/1.json
  def destroy
    @sales_ad = SalesAd.find(params[:id])
    @sales_ad.destroy

    respond_to do |format|
      format.html { redirect_to sales_ads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sales_ads_helper.rb
module SalesAdsHelper
end

app/views/sales_ads/_form.html.erb
<%= form_for(@sales_ad) do |f| %>
  <% if @sales_ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sales_ad.errors.count, "error") %> prohibited this sales_ad from being saved:</h2>

      <ul>
      <% @sales_ad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= stepper f %>
<% end %>

app/views/sales_ads/_price_quantity_frequency_step.html.erb
<div class="field">
  <%= f.label :quantity %><br />
  <%= f.text_field :quantity %>
</div>
<div class="field">
  <%= f.label :unit %><br />
  <%= f.text_field :unit %>
</div>
<div class="field">
  <%= f.label :unit_price %><br />
  <%= f.text_field :unit_price %>
</div>
<div class="field">
  <%= f.label :total_price %><br />
  <%= f.text_field :total_price %>
</div>
<div class="field">
  <%= f.label :show_price %><br />
  <label>Não</label>
  <%= f.radio_button :show_price, false %>
  <label>Sim</label>
  <%= f.radio_button :show_price, true %>
</div>
<div class="field">
  <%= f.label :frequency_removal_waste %><br />
  <%= f.text_field :frequency_removal_waste %>
</div>
<div class="field">
  <%= f.label :contract_time %><br />
  <%= f.text_field :contract_time %>
</div>

app/views/sales_ads/edit.html.erb
<h1>Editing sales_ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @sales_ad %> |
<%= link_to 'Back', sales_ads_path %>

app/views/sales_ads/index.html.erb
<h1>Listing sales_ads</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Category</th>
    <th>User type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sales_ads.each do |sales_ad| %>
  <tr>
    <td><%= sales_ad.title %></td>
    <td><%= sales_ad.category_id %></td>
    <td><%= sales_ad.user_type %></td>
    <td><%= link_to 'Show', sales_ad %></td>
    <td><%= link_to 'Edit', edit_sales_ad_path(sales_ad) %></td>
    <td><%= link_to 'Destroy', sales_ad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sales ad', new_sales_ad_path %>

app/views/sales_ads/new.html.erb
<div class="padrao_box">
  <div class="container">
    <div class="row">
      <div class="span12">
        <h5>Escolha o residuo que deseja anunciar</h5>

        <%= render 'form' %>

        <%= link_to 'Back', sales_ads_path %>
      </div>
    </div>
  </div>
</div>

app/views/sales_ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @sales_ad.title %>
</p>

<p>
  <b>Category:</b>
  <%= @sales_ad.category_id %>
</p>

<p>
  <b>User type:</b>
  <%= @sales_ad.user_type %>
</p>


<%= link_to 'Edit', edit_sales_ad_path(@sales_ad) %> |
<%= link_to 'Back', sales_ads_path %>