config/routes.rb
Wasteblue::Application.routes.draw do

  resources :categories

  match "/done" => "purchasing_ads#done"
  match "/atualizar_endereco" => "purchasing_ads#atualizar_endereco"

  get "users/show"

  get "users/index"

  get "legal_entities/show"

  get "legal_entities/index"

  get "faq/view"

  get "policy/view"

  get "terms/view"

  get "press/view"

  get "partners/view"

  get "about/view"

  get "awasteblue/view"

  get "login" => "awasteblue#login"

  get "cadastrar" => "awasteblue#cadastrar"

  get "ads/all"

  get "advertise/index"

  get "howto/index"

  get "blog/index"

  get "contato/index"
  get "construction/index"
  
  devise_for :legal_entities
  devise_for :users

  devise_scope :legal_entity do
    get 'pessoa_juridica/sign_in', :to => 'devise/sessions#new', :as => :new_legal_entity_session
    get 'pessoa_juridica/sign_up', :to => 'devise/registrations#new', :as => :new_legal_entity_registration
    get 'pessoa_juridica/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_legal_entity_session
  end

  devise_scope :user do
    get 'pessoa_fisica/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'pessoa_fisica/sign_up', :to => 'devise/registrations#new', :as => :new_user_registration
    get 'pessoa_fisica/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match 'pessoa_juridica/conta/:id' => 'legal_entities#show'
  match 'pessoa_fisica/conta/:id' => 'users#show'

  match 'pessoa_juridica/conta/:id/editar' => 'legal_entities#edit'
  match 'pessoa_fisica/conta/:id/editar' => 'users#edit'

  match 'pessoa_juridica/conta/:id/criar_anuncio/venda' => 'sales_ads#new'
  match 'pessoa_fisica/conta/:id/criar_anuncio/venda' => 'sales_ads#new'

  match 'pessoa_juridica/conta/:id/criar_anuncio/compra' => 'purchasing_ads#new'
  match 'pessoa_fisica/conta/:id/criar_anuncio/compra' => 'purchasing_ads#new'

  resources :legal_entities
  resources :posts
  resources :users
  resources :sales_ads
  resources :purchasing_ads

 
  root :to => 'pages#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :waste_name

  acts_as_taggable
  acts_as_taggable_on :waste_name

end

app/models/legal_entity.rb
class LegalEntity < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :contact_name, :telephone_home, :telephone_cell, :address, :district, :city, :state, :postal_code, :email, :password, :password_confirmation, :remember_me, :company_name, :cnpj, :fancy_name, :area_of_activity, :waste_generated, :website, :type_of_company
  # attr_accessible :title, :body

  def formulario_completo?
    unless self.contact_name.blank? or self.telephone_home.blank? or self.telephone_cell.blank? or self.district.blank? or self.address.blank? or self.city.blank? or self.state.blank? or self.postal_code.blank? or self.email.blank? or self.company_name.blank? or self.fancy_name.blank? or self.cnpj.blank? or self.area_of_activity.blank? or self.website.blank? or self.waste_generated.blank? or self.type_of_company.blank?
      return true
    end
      return false
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :author, :content, :title, :when
end

app/models/purchasing_ad.rb
class PurchasingAd < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  mount_uploader :picture_details, PictureDetailsUploader
  mount_uploader :picture_extra, PictureExtraUploader
  mount_uploader :picture_greatness, PictureGreatnessUploader
  belongs_to :category  
  attr_accessible :picture,:picture_details,:picture_extra,:picture_greatness,:same_address, :category_id, :title, :user_type, :waste_origin, :details, :quantity,:unit,:unit_price,:total_price,:show_price,:frequency_removal_waste,:contract_time,:today_waste,:transportation_sample,:waste_address,:postal_code,:address_complete,:district,:state,:city,:current_step,:waste_name
end

app/models/sales_ad.rb
class SalesAd < ActiveRecord::Base
  has_steps :steps => %w{ waste_description title_details price_quantity_frequency sample_transport_address }

  attr_accessible :category_id, :title, :user_type, :waste_origin, :details, :quantity,:unit,:unit_price,:total_price,:show_price,:frequency_removal_waste,:contract_time,:today_waste,:transportation_sample,:waste_address,:postal_code,:address_complete,:district,:state,:city,:current_step,:waste_name


  def validate_waste_description
    self.validates_presence_of :category_id
    self.validates_presence_of :waste_name
  end

  def validate_title_details
    self.validates_presence_of :title
    self.validates_presence_of :waste_origin
    self.validates_presence_of :details
  end

  def validate_price_quantity_frequency
    self.validates_presence_of :quantity
    self.validates_presence_of :unit
    self.validates_presence_of :unit_price
    self.validates_presence_of :total_price
    self.validates_presence_of :show_price
    self.validates_inclusion_of :show_price, :in => [true, false]
    self.validates_presence_of :frequency_removal_waste
    self.validates_presence_of :contract_time
  end

  def validate_sample_transport_address
    self.validates_presence_of :today_waste
    self.validates_presence_of :transportation_sample
    self.validates_presence_of :waste_address
    self.validates_presence_of :postal_code
    self.validates_presence_of :address_complete
    self.validates_presence_of :district
    self.validates_presence_of :state
    self.validates_presence_of :city
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,  :name, :telephone_home, :telephone_cell, :address, :district, :city, :state, :postal_code, :cpf, :area_of_activity, :waste_generated, :website, :type_of_user
  # attr_accessible :title, :body

  def formulario_completo?
    unless self.name.blank? or self.telephone_home.blank? or self.telephone_cell.blank? or self.district.blank? or self.address.blank? or self.city.blank? or self.state.blank? or self.postal_code.blank? or self.email.blank? or self.waste_generated.blank? or self.type_of_user.blank?
      return true
    end
      return false
  end
end

app/controllers/awasteblue_controller.rb
class AwasteblueController < ApplicationController
  def view
  end

  def login
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/advertise_helper.rb
module AdvertiseHelper
end

app/helpers/awasteblue_helper.rb
module AwasteblueHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  #Gambi pra funcionar 2 form pra login
  def resource_name_entity
    :legal_entity
  end

  def resource_entity
    @resource ||= LegalEntity.new
  end

  def devise_mapping_entity
    @devise_mapping ||= Devise.mappings[:legal_entity]
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/howto_helper.rb
module HowtoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/policy_helper.rb
module PolicyHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/press_helper.rb
module PressHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/awasteblue/cadastrar.html.erb
<div class="padrao_box">

<div class="form_padrao">
<h2>Logar</h2>
<br>
<section class="login login_fisica">
  <h4>Pessoa Fisica</h4>
  <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
    <div><%= f.label :email, :style => "font-weight:bold;"%><br />
  <%= f.email_field :email, :style => "width: 300px; height:30px; border:1px solid #00a0db;",:placeholder => "digite o seu email", :autofocus => true %></div>

  <div><%= f.label :senha, :style => "font-weight:bold;" %><br />
  <%= f.password_field :password, :style => "width: 300px; height:30px; border:1px solid #00a0db;",:placeholder => "sua senha" %></div>

  <div><%= f.label :confirmar_senha, :style => "font-weight:bold;" %><br />
  <%= f.password_field :password_confirmation, :style => "width: 300px; height:30px; border:1px solid #00a0db;",:placeholder => "confirme sua senha" %></div>
<br />
  <div><%= f.submit "Cadastrar", :style => "width:250px; height:30px; background:#00a0db; border:0px; color:white; padding:5px;" %></div>
  <% end %>

  <%= render "devise/shared/links" %>
</section>

<section class="login login_juridica">
  <h4>Pessoa Juridica</h4>
  <%= form_for(resource_entity, :as => resource_name_entity, :url => registration_path(resource_name_entity)) do |f| %>
    <div><%= f.label :email, :style => "font-weight:bold;"%><br />
  <%= f.email_field :email, :style => "width: 300px; height:30px; border:1px solid #00a0db;",:placeholder => "digite o seu email", :autofocus => true %></div>

  <div><%= f.label :senha, :style => "font-weight:bold;" %><br />
  <%= f.password_field :password, :style => "width: 300px; height:30px; border:1px solid #00a0db;",:placeholder => "sua senha" %></div>

  <div><%= f.label :confirmar_senha, :style => "font-weight:bold;" %><br />
  <%= f.password_field :password_confirmation, :style => "width: 300px; height:30px; border:1px solid #00a0db;",:placeholder => "confirme sua senha" %></div>
<br />
  <div><%= f.submit "Cadastrar", :style => "width:250px; height:30px; background:#00a0db; border:0px; color:white; padding:5px;" %></div>
  <% end %>

  <%= render "devise/shared/links" %>
</section>

</div>

</div>

app/views/awasteblue/login.html.erb
<div class="padrao_box">

<div class="form_padrao">
<h2>Logar</h2>
<br>
<section class="login login_fisica">
  <h4>Pessoa Fisica</h4>
  <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
    <div><%= f.label :email, :style => "font-weight:bold;" %><br />
    <%= f.email_field :email, :style => "width: 300px; height:30px; border:1px solid #00a0db;",:placeholder => "digite o seu email", :autofocus => true %></div>

    <div><%= f.label :senha, :style => "font-weight:bold;" %><br />
    <%= f.password_field :password, :style => "width: 300px; height:30px; border:1px solid #00a0db;",:placeholder => "sua senha" %></div>

    <% if devise_mapping.rememberable? -%>
      <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
    <% end -%>

    <div><%= f.submit "Logar", :style => "width:250px; height:30px; background:#00a0db; border:0px; color:white; padding:5px;" %></div>
  <% end %>

  <%= render "devise/shared/links" %>
</section>

<section class="login login_juridica">
  <h4>Pessoa Juridica</h4>
  <%= form_for(resource_entity, :as => resource_name_entity, :url => session_path(resource_name_entity)) do |f| %>
    <div><%= f.label :email, :style => "font-weight:bold;" %><br />
    <%= f.email_field :email, :style => "width: 300px; height:30px; border:1px solid #00a0db;",:placeholder => "digite o seu email", :autofocus => true %></div>

    <div><%= f.label :senha, :style => "font-weight:bold;" %><br />
    <%= f.password_field :password, :style => "width: 300px; height:30px; border:1px solid #00a0db;",:placeholder => "sua senha" %></div>

    <% if devise_mapping_entity.rememberable? -%>
      <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
    <% end -%>

    <div><%= f.submit "Logar", :style => "width:250px; height:30px; background:#00a0db; border:0px; color:white; padding:5px;" %></div>
  <% end %>

  <%= render "devise/shared/links" %>
</section>

</div>

</div>

app/views/awasteblue/view.html.erb
<div class="clear"></div>
		<div class="inner-head">
		<div class="container">
		<div class="row">
			<div class="span6">
				<h3>A WasteBlue.com</h3>
			</div>
			

		</div>

		</div>
		</div>
		<div class="row">
		
		
			<div class="clear"></div>
			
			<div class="span6">
			<h4></h4>
			<p>A partir da problemática da atual situação do comércio de resíduos no Brasil a WasteBlue.com vem com uma ideia inovadora para solucionar os problemas de empresas e de cidadãos comuns como eu e você.<br /> <br>Somos uma plataforma de comercialização de resíduos que integra todos meios envolvidos, desde empresas que dentro do ciclo de vida de seus produtos são obrigados a se responsabilizar pelos resíduos gerados até os cidadãos preocupados com a destinação final mais sustentável de seus detritos, unindo assim esses “vendedores/geradores” com os “compradores” que utilizam destes produtos como insumos em sua produção, as empresas facilitadoras que possivelmente podem se envolver na negociação, transportadoras e consultorias ambientais. </p>
			</div>
			
			<div class="span6">
			<h4></h4>
			<p>
				 Buscando uma transformação dos passivos ambientais em ativos financeiros, a Wasteblue.com conecta todos os interessados em um só espaço virtual de fácil acesso e simples negociação.<br><br>
				Sejam toneladas de bagaço de cana-de-açucar produzidos por uma Usina, ou alguns quilos de alumínio reciclados ofertados por uma cooperativa de catadores, são muitos os tipos de materias reaproveitados que podem ser comercializados.  </p>
			</div>
			
			<br class="clear" />
			<br class="clear" />
		</div>
		<div class="center-heading">
					<span>Nossa equipe</span>
			</div>
			<div class="clear"></div>

			<div class="usquare_module_shade"></div>
			<div class="clear"></div>
				<div class="span4 people">
					<img src="/files/p1.jpg" alt="" />
					<h5>Paulo Sérgio Bertazzi Rodriguez</h5>
					<span class="post">Co-Founder | CEO</span>
					<p>
						Graduado em Engenharia Ambiental pela Universidade Federal do Mato Grosso do Sul - UFMS e mestre em Tecnologias Ambientais pela mesma instituição de ensino. Atualmente professor na instituição de Ensino Superior Estácio de Sá nos cursos tecnológicos de Gestão Ambiental e de Segurança do Trabalho no Campus de Campo Grande – MS. Aficionado por ideias inovadoras no setor busca em seus projetos implantar ideias simples e acessíveis a toda as classes da sociedade.
					</p>
					
					<section class="social">
			
						<ul>
					
							<li>
							<a href="#" class="facebook">
							<span class="icon-facebook"></span>
							</a>
							</li>
							
							<li><a href="#" class="twitter"><span class="icon-twitter"></span></a>
							</li>
							
							<li>
							<a href="#" class="google-plus">
							<span class="icon-google-plus">        </span>
							</a>
							
							</li>
						</ul>
					
					</section>
				</div>
				<div class="span4 people">
					<img src="/files/p2.jpg" alt="" />
					<h5>Lauren Feder</h5>
					<span class="post">Gerente de Marketing</span>
					<p>Publicitária, graduada na Faculdade Estácio de Sá de Campo Grande, pós graduanda em comunicação e marketing pela mesma instituição e mestranda em comunicação pela Universidade Federal de Mato Grosso do Sul, onde direciona suas pesquisas para o meio ambiente. Sedenta por soluções inovadoras, integra a equipe WasteBlue.com na gerência de comunicação e marketing da empresa.</p>
					
					<section class="social">
			
						<ul>
					
							<li>
							<a href="#" class="facebook">
							<span class="icon-facebook"></span>
							</a>
							</li>
							
							<li><a href="#" class="twitter"><span class="icon-twitter"></span></a>
							</li>
							
							<li>
							<a href="#" class="google-plus">
							<span class="icon-google-plus">        </span>
							</a>
							
							</li>
						</ul>
					
					</section>
				</div>			

			<br class="clear" />
			<br class="clear" />
			<br class="clear" />
			<br class="clear" />
				
			
				<div class="contact-box blue span12">
					<div class="arrow-circle">
					</div>
				<h4>Receba novidades diretamente em seu email.</h4>
				<a class="buttonred" href="http://eepurl.com/vGsWT">Assine nossa newsletter</a>
				</div>