config/routes.rb
Wasteblue::Application.routes.draw do

  resources :categories

  match "/done" => "purchasing_ads#done"
  match "/atualizar_endereco" => "purchasing_ads#atualizar_endereco"

  get "users/show"

  get "users/index"

  get "legal_entities/show"

  get "legal_entities/index"

  get "faq/view"

  get "policy/view"

  get "terms/view"

  get "press/view"

  get "partners/view"

  get "about/view"

  get "awasteblue/view"

  get "login" => "awasteblue#login"

  get "cadastrar" => "awasteblue#cadastrar"

  get "ads/all"

  get "advertise/index"

  get "howto/index"

  get "blog/index"

  get "contato/index"
  get "construction/index"
  
  devise_for :legal_entities
  devise_for :users

  devise_scope :legal_entity do
    get 'pessoa_juridica/sign_in', :to => 'devise/sessions#new', :as => :new_legal_entity_session
    get 'pessoa_juridica/sign_up', :to => 'devise/registrations#new', :as => :new_legal_entity_registration
    get 'pessoa_juridica/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_legal_entity_session
  end

  devise_scope :user do
    get 'pessoa_fisica/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'pessoa_fisica/sign_up', :to => 'devise/registrations#new', :as => :new_user_registration
    get 'pessoa_fisica/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match 'pessoa_juridica/conta/:id' => 'legal_entities#show'
  match 'pessoa_fisica/conta/:id' => 'users#show'

  match 'pessoa_juridica/conta/:id/editar' => 'legal_entities#edit'
  match 'pessoa_fisica/conta/:id/editar' => 'users#edit'

  match 'pessoa_juridica/conta/:id/criar_anuncio/venda' => 'sales_ads#new'
  match 'pessoa_fisica/conta/:id/criar_anuncio/venda' => 'sales_ads#new'

  match 'pessoa_juridica/conta/:id/criar_anuncio/compra' => 'purchasing_ads#new'
  match 'pessoa_fisica/conta/:id/criar_anuncio/compra' => 'purchasing_ads#new'

  resources :legal_entities
  resources :posts
  resources :users
  resources :sales_ads
  resources :purchasing_ads

 
  root :to => 'pages#index'

end

app/models/purchasing_ad.rb
class PurchasingAd < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  mount_uploader :picture_details, PictureDetailsUploader
  mount_uploader :picture_extra, PictureExtraUploader
  mount_uploader :picture_greatness, PictureGreatnessUploader
  belongs_to :category  
  attr_accessible :picture,:picture_details,:picture_extra,:picture_greatness,:same_address, :category_id, :title, :user_type, :waste_origin, :details, :quantity,:unit,:unit_price,:total_price,:show_price,:frequency_removal_waste,:contract_time,:today_waste,:transportation_sample,:waste_address,:postal_code,:address_complete,:district,:state,:city,:current_step,:waste_name
end

app/controllers/purchasing_ads_controller.rb
class PurchasingAdsController < ApplicationController
  # GET /purchasing_ads
  # GET /purchasing_ads.json
  def index
    @purchasing_ads = PurchasingAd.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purchasing_ads }
    end
  end

  # GET /purchasing_ads/1
  # GET /purchasing_ads/1.json
  def show
    @purchasing_ad = PurchasingAd.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purchasing_ad }
    end
  end

  # GET /purchasing_ads/new
  # GET /purchasing_ads/new.json
  def new
    @purchasing_ad = PurchasingAd.new
    @categories = Category.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @purchasing_ad }
    end
  end

  # GET /purchasing_ads/1/edit
  def edit
    @categories = Category.all
    @purchasing_ad = PurchasingAd.find(params[:id])
  end

  # POST /purchasing_ads
  # POST /purchasing_ads.json
  def create
    @purchasing_ad = PurchasingAd.new(params[:purchasing_ad])

    if @purchasing_ad.save
      redirect_to @purchasing_ad
    else
      render :new
    end

  end

  # PUT /purchasing_ads/1
  # PUT /purchasing_ads/1.json
  def update
    @purchasing_ad = PurchasingAd.find(params[:id])

    respond_to do |format|
      if @purchasing_ad.update_attributes(params[:purchasing_ad])
        format.html { redirect_to @purchasing_ad, notice: 'Purchasing ad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @purchasing_ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchasing_ads/1
  # DELETE /purchasing_ads/1.json
  def destroy
    @purchasing_ad = PurchasingAd.find(params[:id])
    @purchasing_ad.destroy

    respond_to do |format|
      format.html { redirect_to purchasing_ads_url }
      format.json { head :no_content }
    end
  end

  def done
    category = Category.find(params[:id])
    @tags = category.tags
    respond_to do |format|
      format.js {render :nothing => true}
      format.json {render :json => @tags}
    end
  end

  def atualizar_endereco
    @user = User.find(params[:id])
    respond_to do |format|
      format.js {render :nothing => true}
      format.json {render :json => @user}
    end
  end
end

app/helpers/purchasing_ads_helper.rb
module PurchasingAdsHelper
end

app/views/purchasing_ads/_form.html.erb
<%= form_for(@purchasing_ad, :html => { :multipart => true }) do |f| %>
  <% if @purchasing_ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchasing_ad.errors.count, "error") %> prohibited this purchasing_ad from being saved:</h2>

      <ul>
      <% @purchasing_ad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="span4">
    <div class="name_category">
      1
    </div>
    <div class="title_details" style="display:none">
      2
    </div>
    <div class="waste_transportation_address" style="display:none">
      3
    </div>
    <div class="price_contract" style="display:none">
      4
    </div>
  </div>
  <div class="span7">
    <div class="name_category">
      <h5>Escolha o residuo que deseja anunciar</h5>
      <div class="field">
        <%= f.label "Categoria:" %>
        <%= f.select :category_id, [["Selecione uma categoria de resíduo", 0]]+ @categories.collect { |c| [c.name, c.id]}  %>
      </div>
      <div class="categorias field">
        <%= f.label :waste_name, "Escolha um resíduo" %>
        <ul id="myTags"></ul>
      </div>
      <div class="categorias field">
        <%= f.label :waste_name, "Ou escreva seu próprio resíduo:" %>
        <ul id="purchasing_ad_waste_name" name="purchasing_ad[waste_name]" ></ul>
        <%= f.hidden_field :waste_name %>
      </div>
      <div>
        <%= link_to "Avançar", "#", :class => "btn btn-primary name_category_btn" %>
      </div>
    </div>
    <div class="title_details" style="display:none">
      <h5>1/5. TÍTULO E DESCRIÇÃO</h5>
      <div class="field">
        <%= f.label :title, "Título:" %>
        <%= f.text_field :title, :class => "span6" %>
      </div>
      <div class="field">
        <%= f.label :waste_origin, "Qual a origem desse resíduo:" %>
        <% [ 'Pós-indústria', 'Pós-consumo', 'Outros' ].each do |waste_origin| %>
          <br><%= f.radio_button :waste_origin, waste_origin %>
          <%= waste_origin.humanize %>
        <% end %>
      </div>
      <br>
      <div class="field">
        <%= f.label :details, "Detalhes:" %>
        <%= f.text_area :details, :placeholder => "Fale sobre o seu resíduo, diga se é sujo,
   limpo, prensado, misto, etc", :class => "span6", :style => "height:180px;" %>
      </div>
      <div>
        <%= link_to "Avançar", "#", :class => "btn btn-primary title_details_btn" %>
      </div>
    </div>

    <div class="waste_transportation_address" style="display:none">
      <h5>2/5. AMOSTRA, TRANSPORTE E ENDEREÇO DO RESÍDUO</h5>
      <div class="field">
        <%= f.label :today_waste, "O que é feito atualmente com o residuo atualmente?" %>
        <%= f.text_area :today_waste, :style => "width: 540px;
height: 180px;", :placeholder => "Por exemplo: Utilizo esse material para criar madeira plástica, etc..." %>
      </div>
      <div class="field">
        <%= f.label :transportation_sample, "Transporte e Amostras:" %>
        <label class="label_normal">&nbsp;<%= f.check_box :transportation_sample %>
        Disponibliza Transporte para esse resíduo?
        </label>
        <label class="label_normal">&nbsp;<%= f.check_box :transportation_sample  %>
        Necessita de amostra para esse resíduo?
        </label>
      </div>
      <br>
      <div class="field">
        <%= f.label :same_address, "Endereço do resíduo:" %>
        <label class="label_normal">
        <%= f.radio_button :same_address, true, :class=>"same_address" %>&nbsp;Mesmo Endereço Cadastrado</label>
        <label class="label_normal">
        <%= f.radio_button :same_address, false, :class=>"other_address" %>&nbsp;Outro Endereço</label>
      </div>
      <div class="show_address" style="display:none;">
        <div style="margin-left:0px;" class="field span7">
          <%= f.label :postal_code, "CEP:" %>
          <%= f.text_field :postal_code, :style => "width: 530px;", :placeholder => "CEP - Apenas Numeros" %>
        </div>
        <div style="margin-left:0px;" class="field span7">
          <%= f.label :address_complete, "Endereço Completo:" %>
          <%= f.text_field :address_complete, :style => "width: 530px;", :placeholder => "Ex.: Rua Tal, Sala 02" %>
        </div>
        <div style="margin-left:0px;" class="field span4">
          <%= f.label :district, "Bairro:" %>
          <%= f.text_field :district, :placeholder => "Bairro", :style => "width:280px;" %>
        </div>
        <div class="field span3">
          <%= f.label :state, "Estado:" %>
          <%= f.select :state, option_estados_for_select %>
        </div>
        <div style="margin-left:0px;" class="field span7">
          <%= f.label :city, "Cidade:" %>
          <%= f.text_field :city, :style => "width: 530px;", :placeholder => "Cidade" %>
        </div>
      </div>
      <div style="margin-left:0px;" class="span7">
        <%= link_to "Avançar", "#", :class => "btn btn-primary waste_transportation_address_btn" %>
      </div>
    </div>

    <div class="price_contract" style="display:none">
      <h5>3/5. PREÇO, QUANTIDADE E FREQUÊNCIA</h5>
      <div style="margin-left:0px;" class="field span3">
        <%= f.label :quantity, "Quantidade:" %>
        <%= f.text_field :quantity %>
      </div>
      <div class="field span3">
        <%= f.label :unit, "Unidade:" %>
        <%= f.select :unit, ["Quilogramas","Litros","Unidades","Peças","Metros"] %>
      </div>
      <div style="margin-left:0px;" class="field span3">
        <%= f.label :unit_price, "Preço por Unidade(R$):" %>
        <%= f.text_field :unit_price %>
      </div>
      <div class="span3 field">
        <%= f.label :total_price, "Preço Total(R$):" %>
        <%= f.text_field :total_price %>
      </div>
      <div style="margin-left:0px;" class="field span7">
        <%= f.label :show_price, "Quer mostrar o preço?" %>
        <label style="float:left; margin-right:15px;"><%= f.radio_button :show_price, true %>Sim</label>
        <label><%= f.radio_button :show_price, false %>Não</label>
      </div>
      <div style="margin-left:0px;" class="field span7">
        <%= f.label :frequency_removal_waste, "Frequência de Retirada do Resíduo:" %>
        <%= f.select :frequency_removal_waste, ["Todo dia","Mensal","Semanal", "Única","A Combinar"] %>
      </div>
      <div style="margin-left:0px;" class="field span7">
        <%= f.label :contract_time, "Tempo de contrato com o Interessado:" %>
        <%= f.select :contract_time, ["Todo dia","Mensal","Semanal", "Única","A Combinar"] %>
      </div>
      <div style="margin-left:0px;" class="field span7">
        <%= link_to "Avançar", "#", :class => "btn btn-primary price_contract_btn" %>
      </div>
    </div>
    <div class="pictures" style="display:none">
      <div class="field span7">
        <%= f.label :picture %>
        <%= f.file_field :picture %>
      </div>
      <div class="field span7">
        <%= f.label :picture_details %>
        <%= f.file_field :picture_details %>
      </div>
      <div class="field span7">
        <%= f.label :picture_greatness %>
        <%= f.file_field :picture_greatness %>
      </div>
      <div class="field span7">
        <%= f.label :picture_extra %>
        <%= f.file_field :picture_extra %>
      </div>
      <div class="span7 actions">
        <%= f.submit "Finalizar", :class => "btn btn-primary" %>
      </div>
    </div>
  </div>

  <script>
    $(document).ready(function(){
      $('.other_address').on('change',function(){
        $('.show_address').show('low');
      });
      $('.same_address').on('change', function(){
        $('.show_address').hide('low');
      });
      $('.name_category_btn').on('click',function(){
        $('.name_category').hide('low');
        $('.title_details').show('low');
      });
      $('.title_details_btn').on('click',function(){
        $('.title_details').hide('low');
        $('.waste_transportation_address').show('low');
      });
      $('.waste_transportation_address_btn').on('click', function(){
        $('.waste_transportation_address').hide('low');
        $('.price_contract').show('low');

        if ($('.same_address').is(':checked')){
          $.ajax({
            url: "/atualizar_endereco",
            dataType: 'json',
            beforeSend: function() { console.log("Começa") },
            data: {
              id:<%= current_user.id %>,
            },
            success: function(data) {
              $('#purchasing_ad_postal_code').val(data.postal_code);
              $('#purchasing_ad_address_complete').val(data.address);
              $('#purchasing_ad_district').val(data.district);
              $('#purchasing_ad_city').val(data.city);
            }
          });
        };
      });
      $('.price_contract_btn').on('click', function(){
        $('.price_contract').hide('low');
        $('.pictures').show('low');
      });

      /*Mltiplicação de Unidades por dinheiros*/
      $('#purchasing_ad_unit_price').on('change',function(){
        var quantidade = $('#purchasing_ad_quantity').val();
        var preco_unitario = $(this).val();

        $('#purchasing_ad_total_price').val(quantidade * preco_unitario);
      });
    });
    $("#purchasing_ad_category_id").change(function(){
      $.ajax({
        url: "/done",
        dataType: 'json',
        beforeSend: function() { console.log("Começa") },
        data: {
          id:$(this).val(),
        },
        success: function(data) {
          $("#myTags").tagit();
          $("#myTags").find('li').remove();
          $('.categorias').show('low');
          $.each(data,function(key,value){
            console.log(key+" - "+value.id + " - "+value.name+" ...")
            $("#myTags").append("<li class='tagit-choice ui-widget-content ui-state-default ui-corner-all tagit-choice-read-only' id="+value.id+">"+value.name+"</li>");
          })
        }
      });
    });
    $("#purchasing_ad_category_id").bind("ajaxComplete", function(){
      $('ul#purchasing_ad_waste_name').tagit();
      $('#myTags li').on('click',function(){
        var thisid = $(this).attr('id')
        var thistext = $(this).text()
        console.log(thisid + thistext);
        $('ul#purchasing_ad_waste_name').prepend("<li class='tagit-choice ui-widget-content ui-state-default ui-corner-all tagit-choice-read-only' id="+thisid+">"+thistext+"</li>")
        var cat_name = $('#purchasing_ad_category_id :selected').text()
        $('#purchasing_ad_title').val("Compro "+cat_name+" / "+thistext)
        $('input[type="hidden"]#purchasing_ad_waste_name').text("Compro "+cat_name+" / "+thistext)
      });
    });
    
  </script>
<% end %>

app/views/purchasing_ads/_sample_transport_address_step.html.erb
<div class="field">
  <%= f.label :today_waste %><br />
  <%= f.text_field :today_waste %>
</div>
<div class="field">
  <%= f.label :transportation_sample %><br />
  <%= f.text_field :transportation_sample %>
</div>
<div class="field">
  <%= f.label :waste_address %><br />
  <%= f.text_field :waste_address %>
</div>
<div class="field">
  <%= f.label :postal_code %><br />
  <%= f.text_field :postal_code %>
</div>
<div class="field">
  <%= f.label :address_complete %><br />
  <%= f.text_field :address_complete %>
</div>
<div class="field">
  <%= f.label :district %><br />
  <%= f.text_field :district %>
</div>
<div class="field">
  <%= f.label :state %><br />
  <%= f.text_field :state %>
</div>
<div class="field">
  <%= f.label :city %><br />
  <%= f.text_field :city %>
</div>

app/views/purchasing_ads/_title_details_step.html.erb
<div class="field">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :waste_origin %><br />
  <%= f.text_field :waste_origin %>
</div>
<div class="field">
  <%= f.label :details %><br />
  <%= f.text_field :details %>
</div>

app/views/purchasing_ads/_waste_description_step.html.erb
<h5>Escolha o residuo que deseja anunciar</h5>
<div class="field">
  <%= f.label "Categoria:" %>
  <%= f.select :category_id, [["Selecione uma categoria de resíduo", 0]]+ @categories.collect { |c| [c.name, c.id]}  %>
</div>
<div class="categorias field">
  <%= f.label :waste_name, "Escolha um resíduo" %>
  <ul id="myTags"></ul>
</div>
<div class="categorias field">
  <%= f.label :waste_name, "Ou escreva seu próprio resíduo:" %>
  <ul id="purchasing_ad_waste_name" name="purchasing_ad[waste_name]" ></ul>
</div>
<script>
  $().ready(function(){
    
  });
  $("#purchasing_ad_category_id").change(function(){
    $.ajax({
      url: "/done",
      dataType: 'json',
      beforeSend: function() { alert("Começa") },
      data: {
        id:$(this).val(),
      },
      success: function(data) {
        $("#myTags").tagit();
        $("#myTags").find('li').remove();
        $('.categorias').show();
        $.each(data,function(key,value){
          console.log(key+" - "+value.id + " - "+value.name+" ...")
          $("#myTags").append("<li class='tagit-choice ui-widget-content ui-state-default ui-corner-all tagit-choice-read-only' id="+value.id+">"+value.name+"</li>");
          
        })
      }
    });
  });
  $("#purchasing_ad_category_id").bind("ajaxComplete", function(){
    $('#purchasing_ad_waste_name').tagit();
    $('#myTags li').on('click',function(){
      var thisid = $(this).attr('id')
      var thistext = $(this).text()
      console.log(thisid + thistext);
      $('#purchasing_ad_waste_name').prepend("<li class='tagit-choice ui-widget-content ui-state-default ui-corner-all tagit-choice-read-only' id="+thisid+">"+thistext+"</li>")
    });
  });
  
</script>

app/views/purchasing_ads/edit.html.erb
<h1>Editing purchasing_ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchasing_ad %> |
<%= link_to 'Back', purchasing_ads_path %>

app/views/purchasing_ads/index.html.erb
<section id="sidebar_an">
  <span>
    Violeiro
  </span>
</section>
<section id="content_an">
  <h1>Anuncios</h1>
  <ul id="item_list">
    <% @purchasing_ads.each do |purchasing_ad| %>
      <li class="buy">
        <span class="item_type" style="">Compro</span>
        <%= link_to purchasing_ad, :class=>"a_img" do %>
          <%= image_tag purchasing_ad.picture_url(:thumb) if purchasing_ad.picture? %>
        <% end %>
        <h3 class="item_name">
          <%= link_to purchasing_ad.title, purchasing_ad %>
        </h3>
        <span class="item_description">
          <%= purchasing_ad.details %>
        </span>
        <span class="item_details">
          <strong><%= number_to_currency(purchasing_ad.total_price , :format => "%u %n", :separator => ",", :delimiter => ".", :unit => "R$") %></strong><br>
          <p><%= purchasing_ad.quantity %>/<%= purchasing_ad.unit %></p>
          <p><%= purchasing_ad.city %>-<%= purchasing_ad.state %></p>
        </span>
      </li>
    <% end %>
  </ul>
</section>

app/views/purchasing_ads/new.html.erb
<div class="padrao_box">
  <div class="container">
    <div class="row">
      <div class="span12">
        
        <%= render 'form' %>

      </div>
    </div>
  </div>
</div>

app/views/purchasing_ads/show.html.erb
<section id="sidebar_an">
  <span>
    Violeiro
  </span>
</section>
<section id="content_an">
  <p id="notice"><%= notice %></p>
  <p id="category_link">
    <%= link_to @purchasing_ad.category.name, "/"%>/<%= link_to @purchasing_ad.category.tag_list.first, "/"%>
  </p>
  <article id="item_overview" class="buy">
    <span id="item_type" style="">Compro</span>
    <h2 id="item_title">
      <span><%= @purchasing_ad.title %></span>
      <span id="item_location">(<%= @purchasing_ad.city %>-<%= @purchasing_ad.state %>)</span>
    </h2>
    <div id="item_picture">
      <div id="item_picture_main">
        <%= image_tag @purchasing_ad.picture_url(:throbber) if @purchasing_ad.picture? %>
      </div>
    </div>
    <p>
      <b>Category:</b>
      <%= @purchasing_ad.category_id %>
    </p>

    <p>
      <b>User type:</b>
      <%= @purchasing_ad.user_type %>
    </p>
  </article>
</section>